# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_baixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_alta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_diferenca_alta_baixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_diferenca_compra_baixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_diferenca_venda_baixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('data_criacao', models.DateTimeField()),
            ],
            options={
                'ordering': ('-data_criacao',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='historico',
            unique_together=set([('valor_baixa', 'valor_alta', 'valor_compra', 'valor_venda', 'valor_volume')]),
        ),
    ]
