# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_bitcoin', models.DecimalField(decimal_places=8, max_digits=20)),
                ('data_investimento', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
